# Generated by Django 3.2.3 on 2021-05-30 07:02

import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='Marathon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=300)),
                ('date', models.DateField()),
                ('time', models.TimeField(null=True)),
                ('tag', models.CharField(max_length=200)),
                ('meta_description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, upload_to='uploads/')),
                ('map_image', models.ImageField(blank=True, upload_to='uploads/')),
                ('distance_start', models.IntegerField()),
                ('distance_end', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('affiliation', models.ManyToManyField(blank=True, to='marathon.Affiliation')),
            ],
        ),
        migrations.CreateModel(
            name='MarathonBookingCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'Marathon Booking Categories',
            },
        ),
        migrations.CreateModel(
            name='MarathonCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Marathon Categories',
            },
        ),
        migrations.CreateModel(
            name='MarathonBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_first_name', models.CharField(max_length=200, verbose_name='First Name')),
                ('person_last_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Last Name')),
                ('person_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('person_mobile_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Mobile Number')),
                ('person_gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('T', 'Prefer Not to Answer')], max_length=1, null=True, verbose_name='Gender')),
                ('person_birthdate', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('person_nationality', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nationality')),
                ('person_passport_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='Passport No.')),
                ('address_street_address', models.CharField(max_length=100, verbose_name='Street Address')),
                ('address_address_l2', models.CharField(max_length=100, verbose_name='Address Line 2')),
                ('address_city', models.CharField(max_length=100, verbose_name='City')),
                ('address_state', models.CharField(max_length=100, verbose_name='State / Province / Region')),
                ('address_zip_code', models.IntegerField(verbose_name='ZIP / Postal')),
                ('address_country', django_countries.fields.CountryField(max_length=2)),
                ('arrival_date', models.DateField(verbose_name='Arrival Date')),
                ('departure_date', models.DateField(verbose_name='Departure Date')),
                ('others_text', models.TextField(blank=True, null=True, verbose_name='Other Specify')),
                ('visa_recommend', models.BooleanField(verbose_name='Check if you need Visa Recommendation Letter.')),
                ('agree_policy', models.BooleanField(verbose_name='I agree to the booking policy.')),
                ('marathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marathon.marathon')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='marathon.marathonbookingcategory', verbose_name='Select Package')),
            ],
            options={
                'verbose_name_plural': 'Marathon Bookings',
            },
        ),
        migrations.AddField(
            model_name='marathon',
            name='marathon_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='marathon.marathoncategory'),
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('day', models.IntegerField()),
                ('description', ckeditor.fields.RichTextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marathon.marathon')),
            ],
            options={
                'verbose_name_plural': 'Itineraries',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=400)),
                ('answer', models.CharField(max_length=600)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marathon.marathoncategory')),
            ],
        ),
    ]
