# Generated by Django 3.2.5 on 2021-07-23 08:40

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marathon', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affiliation',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='marathon',
            name='map_image',
        ),
        migrations.AddField(
            model_name='affiliation',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image/affiliation'),
        ),
        migrations.AlterField(
            model_name='marathon',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image/marathon'),
        ),
    ]
