# Generated by Django 3.1.7 on 2021-02-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marathon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='description',
            field=models.TextField(default='this is sample description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slider',
            name='link',
            field=models.URLField(default='www.link.com'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slider',
            name='link_title',
            field=models.CharField(default='sample title', max_length=200),
            preserve_default=False,
        ),
    ]
