# Generated by Django 3.1.7 on 2021-02-28 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marathon', '0002_auto_20210227_2147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testemonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='testemonial/')),
                ('testemonial_text', models.TextField()),
            ],
        ),
    ]
