# Generated by Django 3.1.7 on 2021-03-04 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marathon', '0002_itinerary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
