# Generated by Django 3.1.7 on 2021-02-28 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marathon', '0003_testemonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marathon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('tag', models.CharField(max_length=200)),
                ('marathon_type', models.IntegerField(choices=[(500, 'minimarathon'), (1000, 'marathon')], default=500)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='slider',
            name='image_order',
            field=models.IntegerField(choices=[(1, 'First'), (2, 'Second'), (3, 'Third'), (0, 'None')], default=0),
        ),
    ]
