# Generated by Django 3.1.7 on 2021-03-04 08:19

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marathon', '0005_timer_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marathon',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
