# Generated by Django 3.1.7 on 2021-03-04 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marathon', '0006_auto_20210304_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='marathon',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
    ]
