# Generated by Django 3.1.7 on 2021-03-04 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marathon', '0007_marathon_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='marathon',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
