# Generated by Django 3.1.7 on 2021-03-04 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marathon', '0008_marathon_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='marathon',
            name='map_image',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
    ]
