# Generated by Django 3.1.7 on 2021-03-08 07:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marathon', '0009_marathon_map_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='marathonbooking',
            name='address_address_l2',
            field=models.CharField(max_length=100, verbose_name='Address Line 2'),
        ),
        migrations.AlterField(
            model_name='marathonbooking',
            name='address_city',
            field=models.CharField(max_length=100, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='marathonbooking',
            name='address_state',
            field=models.CharField(max_length=100, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='marathonbooking',
            name='address_street_address',
            field=models.CharField(max_length=100, verbose_name='Street Address'),
        ),
        migrations.AlterField(
            model_name='marathonbooking',
            name='address_zip_Code',
            field=models.IntegerField(verbose_name='ZIP/Postal'),
        ),
        migrations.AlterField(
            model_name='marathonbooking',
            name='arrival_date',
            field=models.DateField(verbose_name='Arrival Date'),
        ),
        migrations.AlterField(
            model_name='marathonbooking',
            name='departure_date',
            field=models.DateField(verbose_name='Departure Date'),
        ),
        migrations.AlterField(
            model_name='marathonbooking',
            name='others_text',
            field=models.TextField(verbose_name='Other Specify'),
        ),
        migrations.AlterField(
            model_name='marathonbooking',
            name='person_birthdate',
            field=models.DateField(null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='marathonbooking',
            name='person_email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='marathonbooking',
            name='person_first_name',
            field=models.CharField(max_length=200, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='marathonbooking',
            name='person_gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('T', 'Prefer Not to Answer')], max_length=1, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='marathonbooking',
            name='person_last_name',
            field=models.CharField(max_length=200, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='marathonbooking',
            name='person_mobile_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Mobile Number'),
        ),
        migrations.AlterField(
            model_name='marathonbooking',
            name='person_nationality',
            field=models.CharField(max_length=100, null=True, verbose_name='Nationality'),
        ),
        migrations.AlterField(
            model_name='marathonbooking',
            name='person_passport_no',
            field=models.CharField(max_length=100, null=True, verbose_name='Passport No.'),
        ),
        migrations.AddField(
            model_name='marathon',
            name='affiliation',
            field=models.ManyToManyField(to='marathon.Affiliation'),
        ),
    ]
