# Generated by Django 3.1.7 on 2021-03-08 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marathon', '0010_auto_20210308_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marathon',
            name='affiliation',
        ),
        migrations.DeleteModel(
            name='Affiliation',
        ),
    ]
