# Generated by Django 3.1.7 on 2021-03-08 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marathon', '0011_auto_20210308_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='marathon',
            name='affiliation',
            field=models.ManyToManyField(blank=True, to='marathon.Affiliation'),
        ),
    ]
