# Generated by Django 3.1.7 on 2021-03-08 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marathon', '0015_auto_20210308_1659'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name_plural': 'Galleries'},
        ),
    ]
