# Generated by Django 3.1.7 on 2021-03-08 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marathon', '0017_auto_20210308_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='is_active',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
