# Generated by Django 3.1.7 on 2021-03-08 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marathon', '0018_gallery_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliation',
            name='logo',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
        migrations.CreateModel(
            name='MarathonGallery',
            fields=[
                ('gallery_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='marathon.gallery')),
                ('marathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marathon.marathon')),
            ],
            bases=('marathon.gallery',),
        ),
    ]
