# Generated by Django 3.1.7 on 2021-03-08 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marathon', '0019_auto_20210308_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliation',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
