# Generated by Django 3.1.7 on 2021-03-09 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marathon', '0020_auto_20210308_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marathon',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
