# Generated by Django 3.1.7 on 2021-03-09 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marathon', '0022_auto_20210309_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='description',
            field=models.TextField(),
        ),
    ]
