# Generated by Django 3.1.7 on 2021-03-09 12:19

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marathon', '0023_auto_20210309_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
