# Generated by Django 3.1.7 on 2021-03-19 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marathon', '0024_auto_20210309_1804'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name_plural': 'Home Gallery'},
        ),
        migrations.AlterModelOptions(
            name='itinerary',
            options={'verbose_name_plural': 'Itineraries'},
        ),
        migrations.AlterModelOptions(
            name='marathonbooking',
            options={'verbose_name_plural': 'Marathon Bookings'},
        ),
        migrations.AlterModelOptions(
            name='timer',
            options={'verbose_name_plural': 'Home Timer'},
        ),
        migrations.RemoveField(
            model_name='timer',
            name='time',
        ),
    ]
