# Generated by Django 3.1.7 on 2021-03-19 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marathon', '0027_gallerycategory_kscgallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerycategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
