# Generated by Django 3.1.7 on 2021-03-19 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marathon', '0028_gallerycategory_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='kscgallery',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
