# Generated by Django 3.1.7 on 2021-03-19 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marathon', '0029_kscgallery_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kscgallery',
            name='image',
        ),
        migrations.CreateModel(
            name='ImageGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='marathon.kscgallery')),
            ],
        ),
    ]
