# Generated by Django 3.1.7 on 2021-03-21 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marathon', '0030_auto_20210319_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagegallery',
            name='gallery',
        ),
        migrations.RemoveField(
            model_name='kscgallery',
            name='category',
        ),
        migrations.RemoveField(
            model_name='marathongallery',
            name='gallery_ptr',
        ),
        migrations.RemoveField(
            model_name='marathongallery',
            name='marathon',
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name_plural': 'Sliders'},
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
        migrations.DeleteModel(
            name='GalleryCategory',
        ),
        migrations.DeleteModel(
            name='ImageGallery',
        ),
        migrations.DeleteModel(
            name='KSCGallery',
        ),
        migrations.DeleteModel(
            name='MarathonGallery',
        ),
    ]
