# Generated by Django 3.1.7 on 2021-03-22 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marathon', '0031_auto_20210321_1807'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slider',
        ),
        migrations.DeleteModel(
            name='Testemonial',
        ),
        migrations.DeleteModel(
            name='Timer',
        ),
    ]
