# Generated by Django 3.1.7 on 2021-03-22 14:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('marathon', '0032_auto_20210322_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marathon',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
