# Generated by Django 3.1.7 on 2021-03-22 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marathon', '0035_auto_20210322_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='marathon',
            name='slug',
            field=models.SlugField(default='brand-name', max_length=300),
        ),
    ]
