# Generated by Django 3.2.3 on 2021-05-29 18:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marathon', '0038_auto_20210418_0848'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marathonbooking',
            old_name='address_zip_Code',
            new_name='address_zip_code',
        ),
        migrations.AlterField(
            model_name='marathonbooking',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='marathon.marathonbookingcategory', verbose_name='Select Package'),
        ),
        migrations.AlterField(
            model_name='marathonbooking',
            name='person_gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('T', 'Prefer Not to Answer')], max_length=1, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='marathonbooking',
            name='person_last_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='marathonbooking',
            name='person_mobile_number',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Mobile Number'),
        ),
    ]
