# Generated by Django 3.2.3 on 2021-05-30 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marathon', '0039_auto_20210529_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marathonbooking',
            name='address_state',
            field=models.CharField(max_length=100, verbose_name='State / Province / Region'),
        ),
        migrations.AlterField(
            model_name='marathonbooking',
            name='address_zip_code',
            field=models.IntegerField(verbose_name='ZIP / Postal'),
        ),
        migrations.AlterField(
            model_name='marathonbooking',
            name='agree_policy',
            field=models.BooleanField(verbose_name='I agree to the booking policy.'),
        ),
        migrations.AlterField(
            model_name='marathonbooking',
            name='others_text',
            field=models.TextField(blank=True, null=True, verbose_name='Other Specify'),
        ),
        migrations.AlterField(
            model_name='marathonbooking',
            name='person_birthdate',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='marathonbooking',
            name='person_nationality',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nationality'),
        ),
        migrations.AlterField(
            model_name='marathonbooking',
            name='person_passport_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Passport No.'),
        ),
        migrations.AlterField(
            model_name='marathonbooking',
            name='visa_recommend',
            field=models.BooleanField(verbose_name='Check if you need Visa Recommendation Letter.'),
        ),
    ]
