# Generated by Django 3.2.3 on 2021-05-30 06:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('marathon', '0040_auto_20210530_0616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marathon',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
