# Generated by Django 3.2.3 on 2021-05-30 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marathon', '0041_alter_marathon_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marathon',
            name='id',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False),
        ),
    ]
