# Generated by Django 3.2.5 on 2021-07-23 08:38

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20210322_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagegallery',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image/gallery'),
        ),
    ]
