# Generated by Django 3.2.3 on 2021-05-30 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marathon', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='slider/')),
                ('image_order', models.IntegerField(choices=[(1, 'First'), (2, 'Second'), (3, 'Third'), (0, 'None')], default=0)),
                ('link', models.URLField()),
                ('link_title', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Sliders',
            },
        ),
        migrations.CreateModel(
            name='Testemonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='testemonial/')),
                ('testemonial_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('marathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marathon.marathon')),
            ],
            options={
                'verbose_name_plural': 'Home Timer',
            },
        ),
    ]
